org.gradle.jvmargs=-Xmx1G -XX:+UseG1GC
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=keyboardable_controllable_addon
mod_name=Keyboardable - Controllable Addon
mod_version=0.1.0
mod_group_id=com.krson.keyboardablecontrollableaddon
mod_license=MIT
mod_authors=krson
mod_description=Keyboardable addon for Controllable with controller-friendly keyboard input.
