modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="citrus"
logoFile="icon.png"
description='''
Keyboardable addon for Controllable with controller-friendly keyboard input.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="controllable"
mandatory=true
versionRange="[0.21.9,)"
ordering="AFTER"
side="CLIENT"
